name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'pkg/**'
      - '.github/**'
      - 'proto/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Before cache
        run: |
          mkdir -p ~/go/pkg/mod
          ls ~/go/pkg/

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: After cache
        run: |
          echo "-->${{steps.cache-go.outputs.cache-hit}}<--"

      - name: Get dependencies
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: go get -v -t -d ./...

      - name: Test
        run: make test