name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'pkg/**'
      - '.github/**'
      - 'proto/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: make test